import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Terms of Service',
    description: 'Terms of Service for xml2compose.dev - Review our terms and conditions for using our services.',
};

export default function TermsPage() {
    return (
        <div className="container">
            <section className="about-section">
                <div className="container">
                    <h2>Terms of Service</h2>
                    <p><strong>Last Updated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

                    <div style={{ marginTop: '32px' }}>
                        <h3>1. Acceptance of Terms</h3>
                        <p>
                            By accessing and using xml2compose.dev (&quot;the Service&quot;), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.
                        </p>

                        <h3 style={{ marginTop: '32px' }}>2. Description of Service</h3>
                        <p>
                            xml2compose.dev provides an online tool that converts Android XML layout files to Jetpack Compose code. The Service includes:
                        </p>
                        <ul style={{ paddingLeft: '24px', marginBottom: '16px' }}>
                            <li>XML to Compose code conversion tool</li>
                            <li>Technical blog articles and tutorials</li>
                            <li>Documentation and best practices guides</li>
                        </ul>

                        <h3 style={{ marginTop: '32px' }}>3. Use of Service</h3>
                        <p>You agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to:</p>
                        <ul style={{ paddingLeft: '24px', marginBottom: '16px' }}>
                            <li>Use the Service in any way that violates applicable laws or regulations</li>
                            <li>Attempt to gain unauthorized access to our systems</li>
                            <li>Use automated scripts to access the Service without permission</li>
                            <li>Interfere with or disrupt the Service or servers</li>
                        </ul>

                        <h3 style={{ marginTop: '32px' }}>4. Intellectual Property</h3>
                        <p>
                            The Service, including its original content, features, and functionality, is owned by xml2compose.dev and is protected by international copyright, trademark, and other intellectual property laws.
                        </p>
                        <p>
                            Code generated by our converter tool is provided for your use in your projects. You retain all rights to your original XML files and the converted output.
                        </p>

                        <h3 style={{ marginTop: '32px' }}>5. User Content</h3>
                        <p>
                            When you upload XML files to our converter:
                        </p>
                        <ul style={{ paddingLeft: '24px', marginBottom: '16px' }}>
                            <li>All processing happens client-side in your browser</li>
                            <li>We do not store, collect, or transmit your uploaded files</li>
                            <li>You are responsible for the content you upload</li>
                        </ul>

                        <h3 style={{ marginTop: '32px' }}>6. Disclaimer of Warranties</h3>
                        <p>
                            The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either express or implied. We do not guarantee that:
                        </p>
                        <ul style={{ paddingLeft: '24px', marginBottom: '16px' }}>
                            <li>The Service will be uninterrupted or error-free</li>
                            <li>Converted code will be 100% accurate or production-ready</li>
                            <li>The Service will meet your specific requirements</li>
                        </ul>

                        <h3 style={{ marginTop: '32px' }}>7. Limitation of Liability</h3>
                        <p>
                            In no event shall xml2compose.dev be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or related to your use of the Service.
                        </p>

                        <h3 style={{ marginTop: '32px' }}>8. Changes to Terms</h3>
                        <p>
                            We reserve the right to modify these Terms at any time. We will notify users of significant changes by updating the &quot;Last Updated&quot; date. Continued use of the Service after changes constitutes acceptance of the new Terms.
                        </p>

                        <h3 style={{ marginTop: '32px' }}>9. Governing Law</h3>
                        <p>
                            These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.
                        </p>

                        <h3 style={{ marginTop: '32px' }}>10. Contact Us</h3>
                        <p>
                            If you have questions about these Terms of Service, please contact us at <strong>support@xml2compose.dev</strong>.
                        </p>
                    </div>

                    <div style={{ marginTop: '48px', padding: '24px', background: 'rgba(0, 122, 255, 0.1)', borderRadius: '12px', border: '1px solid rgba(0, 122, 255, 0.3)' }}>
                        <p style={{ margin: 0 }}>
                            <strong>Note:</strong> By using xml2compose.dev, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
                        </p>
                    </div>
                </div>
            </section>
        </div>
    );
}
